### ISSUE TITLE
How to compile project?

### ISSUE THREAD

**Issue by RodrigoCMoraes** [TimChinenov/GraspPicture#1]
I have tried:

g++ main.cpp -o main `pkg-config --cflags --libs opencv` *.h *.cpp -lm

But does not work. Can you help me?

**Comment by TimChinenov** [comment]
Hi, I've added files to this program since I made my original post about it. I would simply use:
`g++ -std=c++11 *.cpp `pkg-config --libs --cflags opencv` -o main`
Let me know if this doesn't work.

**Comment by RodrigoCMoraes** [comment]
Thanks for quickly answer.

With c++11 some errors has disappeared, but others persists. And I think that this version of code has others issues, for example:

1. On file slic.cpp at line 34, intr is miss type;
2. On file slic.cpp at line 58, missing parenthesis;

I detect others errors, but can't fix than, because I don't understand all code. If you fix these code answer, please let me know.

**Comment by TimChinenov** [comment]
I forgot to remove those two files from the program. You don't need slic.cpp or slic.h. I have updated the repo to remove those files. Let me know if that fixes it.

**Comment by RodrigoCMoraes** [comment]
Now with your last updates I can compile, no errors nor warnings, but when I try to execute I am getting this error:
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.2) /opencv-3.4.2/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'

Aborted (core dumped)
```

What is your OpenCV Version?

**Comment by TimChinenov** [comment]
Last I checked, I was using 3.3.1

**Comment by RodrigoCMoraes** [comment]
The problem was solved when I pass filename image as input of binary execution.

Thanks for everything.
